# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Katherine Shakman, PhD
title: Field Data Scientist
email: katieshak@gmail.com
# email_title: Email (Email title override)
phone: 773-882-8262
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
linkedin_username: katherine-shakman
# twitter_username: markovchainmail
github_username:  katieshakman
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll

#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
#orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/Katie_Snowshoe_Cropped_Small.jpg #Google Profile Picture.png #insight-headshot-linkedin-version.jpeg
about_content: | # this will include new lines to allow paragraphs
 I'm a data scientist and engineer with a PhD in neuroscience and 3 years of experience in the data science and software industry.  
 I collaborate with data science teams to implement advanced solutions across a variety of domains. 
 I employ my skills in experimental design, problem solving, project management, analytics, machine learning, data visualization and technical communication 
 to deliver fast and high quality solutions to complex problems. 


content:
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Programming Languages and Tools
        description: | # this will include new lines to allow paragraphs
          Python, R, MATLAB, MQL (MongoDB), SQL, Bash, Pandas, Numpy, Ray, Spark, Horovod, Matplotlib, Seaborn, Scikit-learn, Torch, Tensorflow/Keras, AWS, PyMongo, Git, Unix
# Scientific: Experimental design, statistical analysis, data visualization, technical communication
# Machine Learning and Algorithms: Linear and logistic regression, decision trees and random forest, k- nearest neighbors, support vector machines, k-means clustering, principal components analysis and dimensionality reduction, neural networks, natural language processing 

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: center
        title: Accelerating Model Training and Hyperparameter Optimization on Multiple Nvidia GPUs with Distributed Computing on Domino 
        link: https://www.dominodatalab.com/resources/how-janssen-r-d-accelerated-model-training-on-multi-gpu-machines-for-faster-cancer-cell-identification/
        link_text: How Janssen R&D Accelerated Model Training on Multi-GPU Machines for Faster Cancer Cell Identification
        additional_links:
          - title:  Conference Talk LinkedIn Announcement 
            icon: fab fa-linkedin
            url: https://www.linkedin.com/posts/katherine-shakman_gtc20-computervision-jnjdatascience-activity-6720000143309074432-WmOl
#         quote: >
#           Collaboration to optimize and accelerate training of an image recognition model using Spark, Horovod, and Ray.io Tune on the Domino platform.  
        description: | 
          Collaboration to optimize and accelerate training of an image recognition model using Spark, Horovod, and Ray.io Tune on the Domino platform.
          About Domino: Domino's enterprise MLOps platform accelerates research, speeds model deployment, and increases collaboration for code-first data science teams at scale.
      - layout: center
        title: Therapulse - Predicting Patient Distress Levels  
#         link: https://www.dominodatalab.com/resources/how-janssen-r-d-accelerated-model-training-on-multi-gpu-machines-for-faster-cancer-cell-identification/
#         link_text: How Janssen R&D Accelerated Model Training on Multi-GPU Machines for Faster Cancer Cell Identification
#         additional_links:
#           - title:  Conference Talk LinkedIn Announcement 
#             icon: fab fa-linkedin
#             url: https://www.linkedin.com/posts/katherine-shakman_gtc20-computervision-jnjdatascience-activity-6720000143309074432-WmOl
        description: | 
          Consulted for Therachat, a company that helps therapists and patients connect in between talk therapy sessions.  I built TheraPulse, a tool for predicting patients’ symptom severity, using NLP, SVM, Random Forest, and grid search hyperparameter optimization.  The final product was a Dash web app which would predict a user's distress level for the following week.
        quote: >
          Project is not public.  Details available upon request.  
  - title: Experience
    layout: list
    content:
      - layout: center
        title: Domino Data Lab
        sub_title: Field Data Scientist
        caption: May 2020 - Present 
        link: dominodatalab.com
#         quote: >
#           Domino's enterprise MLOps platform accelerates research, speeds model deployment, and increases collaboration for code-first data science teams at scale.
        description: | # this will include new lines to allow paragraphs
          I partner with data scientists at our customers to assist with data science projects from end to end, in as much depth as is needed to ensure the success of their projects.  
  - title: Education
    layout: list
    content:
      - layout: center
        title: Columbia University
        sub_title: PhD in Neuroscience 
        caption: September 2011 - May 2018 
#         quote: >
#           Department of Neuroscience, Columbia University in the City of New York
        description: | # this will include new lines to allow paragraphs
          Department of Neuroscience, Columbia University in the City of New York. 
          Dissertation: Cross-compartmental modulation and plasticity in the Drosophila mushroom body
#   - title: A Little More About Me
#     layout: text
#     content: | # this will include new lines to allow paragraphs
#       This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.
  - title: Resume
    layout: list
    content: 
      - layout: center
        title: Download Resume 
        link: https://github.com/katieshakman/katieshakman.github.io/raw/main/images/Katie_Shakman_Resume_20210417.pdf
        link text: Download Resume 

#       Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)


# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
