# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Katherine Shakman, PhD
title: Field Data Scientist
email: katieshak@gmail.com
# email_title: Email (Email title override)
phone: 773-882-8262
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
linkedin_username: katherine-shakman
# twitter_username: markovchainmail
github_username:  katieshakman
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll

#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
#orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/Katie_Snowshoe_Cropped_Small.jpg #Google Profile Picture.png #insight-headshot-linkedin-version.jpeg
about_content: | # this will include new lines to allow paragraphs
 I'm a data scientist and engineer with a PhD in neuroscience and 3 years of experience in the data science and software industry.  

 I collaborate with data science teams to implement advanced solutions across a variety of domains. 
 I employ my skills in experimental design, problem solving, project management, analytics, machine learning, data visualization and technical communication 
 to deliver fast and high quality solutions to complex problems. 

content:
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: center  
        title: Programming Languages and Tools
        description: | # this will include new lines to allow paragraphs
          **Programming Languages and Tools**: Python\*, R, MATLAB\*, MongoDB\*, SQL, PyMongo, Bash, Pandas\*, Numpy, Ray, Spark, Seaborn, Scikit-learn*, Torch, Tensorflow/Keras, AWS\*, Unix\*, Docker, Kubernetes, Git
          
          **Scientific**: Experimental design\*, statistical analysis\*, data visualization\*, technical communication\*
          
          **Machine Learning and Algorithms**: Linear and logistic regression\*, decision trees and random forest\*, k- nearest neighbors, support vector machines\*, k-means clustering, principal components analysis and dimensionality reduction, neural networks, natural language processing, collaborative filtering
          
          \* = most experience

# Scientific: Experimental design, statistical analysis, data visualization, technical communication
# Machine Learning and Algorithms: Linear and logistic regression, decision trees and random forest, k- nearest neighbors, support vector machines, k-means clustering, principal components analysis and dimensionality reduction, neural networks, natural language processing 

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: center
        title: Streaming Online Learning on an Open Data Science Platform  
        link: https://github.com/dominodatalab/streaming-online-learning
        link_text: Online Learning Deployment for Streaming Applications Repository
#         additional_links:
#           - title:  Title
#             icon: fab fa-linkedin
#             url: link
        description: | 
          Built and benchmarked a proof of concept for online learning for streaming data in collaboration with colleagues and customer. 
      - layout: center  
        title: Accelerating Model Training and Hyperparameter Optimization on Multiple Nvidia GPUs with Distributed Computing on Domino 
        link: https://www.dominodatalab.com/resources/how-janssen-r-d-accelerated-model-training-on-multi-gpu-machines-for-faster-cancer-cell-identification/
        link_text: How Janssen R&D Accelerated Model Training on Multi-GPU Machines for Faster Cancer Cell Identification
        additional_links:
          - title:  Conference Talk LinkedIn Announcement 
            icon: fab fa-linkedin
            url: https://www.linkedin.com/posts/katherine-shakman_gtc20-computervision-jnjdatascience-activity-6720000143309074432-WmOl
#         quote: >
#           Collaboration to optimize and accelerate training of an image recognition model using Spark, Horovod, and Ray.io Tune on the Domino platform.  
        description: | 
          Collaboration to optimize and accelerate training of an image recognition model using Spark, Horovod, and Ray.io Tune on the Domino platform.
          About Domino: Domino's enterprise MLOps platform accelerates research, speeds model deployment, and increases collaboration for code-first data science teams at scale.
      - layout: center
        title: Therapulse - Predicting Patient Distress Levels  
#         link: https://www.dominodatalab.com/resources/how-janssen-r-d-accelerated-model-training-on-multi-gpu-machines-for-faster-cancer-cell-identification/
        link_text: Project is not public. Details available upon request.
#         additional_links:
#           - title:  Conference Talk LinkedIn Announcement 
#             icon: fab fa-linkedin
#             url: https://www.linkedin.com/posts/katherine-shakman_gtc20-computervision-jnjdatascience-activity-6720000143309074432-WmOl
        description: | 
          Consulted for Therachat, a company that helps therapists and patients connect in between talk therapy sessions.  I built TheraPulse, a tool for predicting patients’ symptom severity, using NLP, SVM, Random Forest, and grid search hyperparameter optimization.  The final product was a Dash web app which would predict a user's distress level for the following week.
        # quote: >
        #   Project is not public.  Details available upon request.  
  
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: center
        title: Domino Data Lab
        sub_title: Field Data Scientist 
        caption: May 2020 - Present
        link: dominodatalab.com
#         quote: >
#           Domino's enterprise MLOps platform accelerates research, speeds model deployment, and increases collaboration for code-first data science teams at scale.
        description: | # this will include new lines to allow paragraphs
          I partner with data scientists at our customers to assist with data science projects from end to end, in as much depth as is needed to ensure the success of their projects.  
          -	Co-conceived, piloted, and built out the data science advisory team within professional services. 
          -	Collaborated on implementation and optimization of a distributed deep learning model for tumor detection in whole slide images, resulting in a conference talk at Nvidia GTC 2020.
          -	Contributed design and implementation of a solution for online ML from streams. 
      - layout: center
        title: Domino Data Lab
        sub_title: Field Engineer/Customer Success Engineer
        caption: October 2018 - May 2020 
        link: dominodatalab.com
#         quote: >
#           Domino's enterprise MLOps platform accelerates research, speeds model deployment, and increases collaboration for code-first data science teams at scale.
        description: | # this will include new lines to allow paragraphs
          Empowered data science teams to work more efficiently, collaboratively, and reproducibly.  
          - Educated data science leaders and teams in data science best practices on Domino data science platform.
          -	Engineered solutions to customers’ technical issues, from environment design to model deployment.
          -	Produce tools to enhance the efficiency of the customer success team.
      - layout: center
        title: Insight Data Science
        sub_title: Health Data Science Fellow 
        caption: June 2018 - September 2018 
        link: https://insightfellows.com/health-data
        # quote: >
        #   The Insight Health Data Science Fellowship is "an intensive 7-week program for PhDs and MDs leading to a career in health data science".
        description: | # this will include new lines to allow paragraphs
          Fellow at Insight Health Data Science, which is "an intensive 7-week program for PhDs and MDs leading to a career in health data science".
          - Consulted for Therachat to build TheraPulse, a tool for predicting patients􏰀 symptom severity. 
          - Produced an end-to-end solution from querying a MySQL database to modeling to webapp.
          - Engineered 8 text-derived features using NLP tools in Python.
          - Predicted patient distress ratings via SVM and random forest models with grid search HPO in sklearn.
      - layout: center
        title: Columbia University  
        sub_title: Graduate Research Fellow in Neuroscience 
        caption: August 2011 - May 2018  
        link: https://neuroscience.columbia.edu
        additional_links:
          - title:  Axel Laboratory 
            # icon: fab fa-linkedin
            url: https://www.axellab.columbia.edu
        # quote: >
        #   The Insight Health Data Science Fellowship is "an intensive 7-week program for PhDs and MDs leading to a career in health data science".
        description: | # this will include new lines to allow paragraphs
          - Conceived and led a project that assessed olfactory behavior and neural responses to olfactory stimuli to uncover new roles for dopaminergic neurons in modulating innate and learned responses to odors 
          - Wrote MATLAB programs for analysis of neural data to understand neural activity in memory circuits
          - Imaged and analyzed neural activity in insect dopamine neurons in response to chemosensory stimuli
          - Generated automated MATLAB tools and pipeline to recognize and analyze insect behavior
      - layout: center
        title: Columbia University Neuroscience Outreach
        sub_title: Executive Board Member  
        caption: November 2012 - January 2018  
        link: https://cuno.zuckermaninstitute.columbia.edu/
        # quote: >
        #   The Insight Health Data Science Fellowship is "an intensive 7-week program for PhDs and MDs leading to a career in health data science".
        description: | # this will include new lines to allow paragraphs
          - Designed neuroscience outreach programming for middle and high school students and families
          - Prepared budgets and grants to fund outreach activities
          - Coordinated events with the American Museum of Natural History and the Dana Foundation 

  - title: Education
    layout: list
    content:
      - layout: center
        title: Columbia University
        sub_title: PhD in Neuroscience 
        caption: May 2018 
#         quote: >
#           Department of Neuroscience, Columbia University in the City of New York
        description: | # this will include new lines to allow paragraphs
          Department of Neuroscience, Columbia University in the City of New York. 
          Dissertation: Cross-compartmental modulation and plasticity in the Drosophila mushroom body
      - layout: center
        title: California Institute of Technology (Caltech)
        sub_title: BS in Biology
        caption: May 2011
#         quote: >
#           Department of Neuroscience, Columbia University in the City of New York
        # description: | # this will include new lines to allow paragraphs
        #   Department of Neuroscience, Columbia University in the City of New York. 
        #   Dissertation: Cross-compartmental modulation and plasticity in the Drosophila mushroom body

#   - title: A Little More About Me
#     layout: text
#     content: | # this will include new lines to allow paragraphs
#       This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.
  
  - title: Resume
    layout: list
    content: 
      - layout: text
        title: Download Resume   
        link: https://github.com/katieshakman/katieshakman.github.io/raw/main/images/Katie_Shakman_Resume_20210417.pdf # /images/Katie_Shakman_Resume_20210417.pdf # 
        link_text: Click to Download Resume 
        # content: |  # include new lines/paragraphs
        #   <embed src="/images/Katie_Shakman_Resume_20210417.pdf" type="application/pdf">
# Resume ![Resume PDF](/images/Katie_Shakman_Resume_20210417.png)
# <embed src="/images/Katie_Shakman_Resume_20210417.pdf" type="application/pdf">
#          

#       Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)


# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
